[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
faultline_gate = "9PFPNC6TMNKBCVsm4RoCgVYmqTJJTwnHHuRcysosSCCe"
faultline_treasury = "46zDmEZAYrpwi3k6FsKFf1rPWZDbZEKM21SFzMKzb1a4"

[provider]
cluster = "Localnet"
wallet = ".localnet/payer.json"

[workspace]
members = [
    "programs/faultline_gate",
    "programs/faultline_treasury",
]
