[workspace]
members = [
    "programs/faultline_gate",
    "programs/faultline_treasury",
]
exclude = ["crates/faultline-replay"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

