"use client";
import { Check,CircleAlert,Copy,LoaderCircle,ShieldAlert,Timer,XCircle } from "lucide-react";import { useEffect,useState,type ReactNode } from "react";import type { ActivityEvent,ProposalState,TokenAmount,VerifierResult } from "@/faultline/types";
export const short=(v:string)=>v.length>16?`${v.slice(0,8)}…${v.slice(-6)}`:v;export const formatAmount=(a:TokenAmount)=>`${(BigInt(a.baseUnits)/BigInt(10**a.decimals)).toString()} ${a.symbol}`;
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>}
export function Panel({title,subtitle,children,className=""}:{title?:string;subtitle?:string;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<div className="panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>}{children}</section>}
export function Metric({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="metric"><span>{label}</span><strong className={mono?"mono":""}>{value}</strong></div>}
const labels:Record<ProposalState,string>={draft:"Draft",funded:"Funded",challenging:"Open for counterexamples",verifying:"Verifier replay",approved:"Eligible for guarded execution",rejected:"Upgrade rejected",executed:"Executed",cancelled:"Cancelled",expired:"Expired",emergency_bypassed:"Emergency bypassed"};
export function ProposalStateBadge({state}:{state:ProposalState}){return <span className={`state-badge ${state}`}><i/>{labels[state]}</span>}
export function Copyable({value}:{value:string}){const[copied,setCopied]=useState(false);return <button className="copyable" title={value} onClick={async()=>{await navigator.clipboard?.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}}><code>{short(value)}</code>{copied?<Check size={13}/>:<Copy size={13}/>}</button>}
export function Countdown({deadline}:{deadline?:number}){const[now,setNow]=useState(deadline?deadline-90000:0);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);if(!deadline)return <span className="countdown muted"><Timer size={14}/>Not open</span>;const sec=Math.max(0,Math.ceil((deadline-now)/1000));return <span className="countdown"><Timer size={14}/>{Math.floor(sec/60).toString().padStart(2,"0")}:{(sec%60).toString().padStart(2,"0")} remaining</span>}
export function Timeline({events}:{events:ActivityEvent[]}){return <div className="timeline">{events.length?events.map(e=><div className={`timeline-item ${e.tone}`} key={e.id}><i/><div><strong>{e.title}</strong><p>{e.detail}</p><time>{new Date(e.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time></div></div>):<EmptyState title="No activity yet" body="Protocol events will appear here as the demo advances."/>}</div>}
export function VerifierGrid({results=[]}:{results?:VerifierResult[]}){const list:VerifierResult[]=results.length?results:["A","B","C"].map(x=>({workerId:`Verifier ${x}`,verdict:"pending"}));return <div className="verifier-grid">{list.map(r=><div className={`worker ${r.verdict}`} key={r.workerId}><div className="worker-top"><span className="worker-icon">{r.verdict==="pending"?<LoaderCircle size={16}/>:r.verdict==="reproduced"?<XCircle size={16}/>:<Check size={16}/>}</span><div><strong>{r.workerId}</strong><small>LiteSVM · allowlisted</small></div></div><span className="verdict">{r.verdict.replaceAll("_"," ")}</span>{r.durationMs&&<code>{r.durationMs}ms · {short(r.resultHash??"")}</code>}</div>)}</div>}
export function Quorum({results=[]}:{results?:VerifierResult[]}){const n=results.filter(r=>r.verdict==="reproduced").length;return <div className="quorum"><div><span>Reproduction quorum</span><strong>{n} / 2 required</strong></div><div className="quorum-bar"><i style={{width:`${Math.min(100,n/2*100)}%`}}/></div><small>MVP verifier quorum · permissioned workers</small></div>}
export function EmptyState({title,body}:{title:string;body:string}){return <div className="empty"><CircleAlert size={19}/><strong>{title}</strong><p>{body}</p></div>}
export function SkeletonState(){return <div className="skeleton-stack" aria-label="Loading"><i/><i/><i/></div>}
export function ErrorState({message}:{message:string}){return <div className="error-state" role="alert"><ShieldAlert size={17}/>{message}</div>}
export function PrototypeNote(){return <div className="prototype-note"><span aria-hidden>SIM</span>Prototype simulation — actions update deterministic local state; no transaction is broadcast.</div>}
