"use client";
import { Link } from "react-router-dom";
import { Activity, ArrowUpRight, ShieldCheck } from "lucide-react";
import { Metric, PageHeader, Panel, ProposalStateBadge, Timeline, formatAmount, short } from "@/components/faultline-ui";
import { useFaultlineSnapshot } from "@/faultline/provider";
export default function Home(){const state=useFaultlineSnapshot();const active=state.proposals.find(p=>p.id===state.activeProposalId)??state.proposals.at(-1);return <div className="page-wrap">
<PageHeader eyebrow="Protocol overview" title="Deployment gate" description="Executable safety invariants become enforceable conditions on the guarded upgrade path." action={<Link className="button primary" to={active?`/proposals/${active.id}`:"/proposals/new"}>{active?"Open active proposal":"Create v2 proposal"}<ArrowUpRight size={15}/></Link>}/>
<section className="status-strip"><div><span className="eyebrow">Protected target</span><strong>Faultline Treasury</strong></div><div><span className="eyebrow">Current deployment</span><strong>{state.deployedVersion}</strong></div><div><span className="eyebrow">Guard authority</span><strong className="good"><ShieldCheck size={15}/>Active</strong></div><div><span className="eyebrow">Active gate</span>{active?<ProposalStateBadge state={active.state}/>:<strong>Not started</strong>}</div></section>
<div className="dashboard-grid"><Panel className="hero-panel"><div className="hero-top"><div><span className="kicker"><Activity size={14}/> live control plane</span><h2>{active?`${active.candidateVersion} · ${active.state==="rejected"?"Declared invariant violated":active.state==="executed"?"Upgrade executed":active.state==="approved"?"Eligible for guarded execution":active.state==="challenging"?"Open for counterexamples":"Gate in progress"}`:"Treasury v1 currently deployed"}</h2><p>{active?"Faultline is enforcing the declared policy against the pinned candidate artifacts.":"Create the vulnerable v2 proposal to begin the canonical prototype flow."}</p></div><div className="version-orbit"><span>{state.deployedVersion}</span><small>deployed</small></div></div><div className="metric-grid"><Metric label="Bounty" value={active?formatAmount(active.bounty):"100 fUSDC"}/><Metric label="Quorum" value="2 of 3"/><Metric label="Invariant" value="AUTH-001"/><Metric label="Program hash" value={short(state.deployedHash)} mono/></div><div className="action-row"><Link className="button primary" to="/demo">Run guided demo <ArrowUpRight size={15}/></Link><Link className="button" to="/proposals/new">Review proposal inputs</Link></div></Panel><Panel title="Recent protocol activity" subtitle="Deterministic events from this device"><Timeline events={state.events.slice(0,6)}/></Panel></div>
</div>}
