"use client";
import { useCallback,useEffect,useState } from "react";import Link from "@/components/router-link";import { ArrowRight,Pause,Play,RotateCcw } from "lucide-react";import { PageHeader,Panel,ProposalStateBadge,PrototypeNote,Quorum,Timeline,VerifierGrid,formatAmount,short } from "@/components/faultline-ui";import { useFaultlineClient,useFaultlineSnapshot } from "@/faultline/provider";import { useFaultlineWebMcp } from "@/faultline/webmcp";
export default function DemoPage(){const client=useFaultlineClient(),state=useFaultlineSnapshot();useFaultlineWebMcp(client);const[busy,setBusy]=useState(false),[auto,setAuto]=useState(false),[feedback,setFeedback]=useState("");const active=state.proposals.find(p=>p.id===state.activeProposalId)??state.proposals.at(-1);
 const run=useCallback(async()=>{if(busy||state.complete)return;setBusy(true);const r=await client.advanceDemo();setFeedback(r.ok?r.message:`${r.code}: ${r.message}`);setBusy(false)},[busy,client,state.complete]);
 useEffect(()=>{if(!auto||busy||state.complete)return;const id=setTimeout(()=>void run(),900);return()=>clearTimeout(id)},[auto,busy,state.step,state.complete,run]);
 return <div className="page-wrap"><PageHeader eyebrow="Guided end-to-end demo" title="Control room" description="The complete v2 rejection → v3 guarded execution story, driven by one deterministic protocol state machine." action={<button className="button" onClick={async()=>{setAuto(false);setBusy(true);await client.resetDemo();setFeedback("Canonical demo state restored.");setBusy(false)}} disabled={busy}><RotateCcw size={14}/>Reset</button>}/><PrototypeNote/>
 <div className="demo-grid"><section className={`demo-stage ${active?.state==="rejected"?"danger":active?.state==="executed"?"success":""}`}><div className="step-count">STEP {Math.min(state.step+1,20).toString().padStart(2,"0")} / 20</div><div><span className="eyebrow">Next protocol transition</span><h2>{state.stepTitle}</h2><p>{state.stepDescription}</p></div><div className="demo-actions"><button className="button primary" onClick={()=>void run()} disabled={busy||state.complete}>{busy?"Simulating…":state.complete?"Demo complete":"Run next step"}<ArrowRight size={15}/></button><button className="button" onClick={()=>setAuto(v=>!v)} disabled={state.complete}>{auto?<Pause size={14}/>:<Play size={14}/>} {auto?"Pause":"Autoplay"}</button></div>{feedback&&<output className="feedback" aria-live="polite">{feedback}</output>}</section>
 <div className="demo-side"><Panel title="Live proposal state" subtitle={active?active.id:"No proposal created"}>{active?<><div className="summary-line"><span>Candidate</span><strong>{active.candidateVersion}</strong></div><div className="summary-line"><span>Gate</span><ProposalStateBadge state={active.state}/></div><div className="summary-line"><span>Bounty</span><strong>{formatAmount(active.bounty)}</strong></div><div className="summary-line"><span>Artifact</span><code>{short(active.artifacts[0].hash)}</code></div><Link className="text-link" href={`/proposals/${active.id}`}>Open operational view <ArrowRight size={13}/></Link></>:<p className="muted-copy">Run the first step to bind the v2 candidate.</p>}</Panel><Panel title="Balances" subtitle="Integer base-unit accounting"><div className="balance-row"><span>Protocol treasury</span><strong>{formatAmount(state.treasuryBalance)}</strong></div><div className="balance-row"><span>Hunter</span><strong>{formatAmount(state.hunterBalance)}</strong></div></Panel></div>
 </div><div className="lower-grid"><Panel title="Verifier processes" subtitle="MVP verifier quorum · 2-of-3"><VerifierGrid results={active?.assignment?.results}/><Quorum results={active?.assignment?.results}/><p className="scope-note">“Preserved” applies only to AUTH-001 and the exact replayed trace. Infrastructure failures never count as preserved.</p></Panel><Panel title="Event stream" subtitle="Newest first"><Timeline events={state.events}/></Panel><Panel title="Deployed program" subtitle="Before / after"><div className="program-compare"><div><span>Before</span><strong>v1</strong><code>{short("41f2c6718a01934fb0b2ac755e41b99abc6ad10fe781c928fad0c6a4a02491a7")}</code></div><ArrowRight/><div><span>Current</span><strong>{state.deployedVersion}</strong><code>{short(state.deployedHash)}</code></div></div></Panel></div></div>}
